name: installs 

on: ["push", "pull_request"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: DEBUG
  MAKEFLAGS: -j
  CTEST_PARALLEL_LEVEL: 8

  # First test current default build. (master) (still 1.0.0)
  HIGHS_VERSION: 1.0.0

jobs:
  build_highs:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
 
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: actions/cache@v1
      with:
        path: ./Dependencies
        key: dependencies-${{env.HIGHS_VERSION}}-${{ matrix.os }}

    - name: Clone HiGHS
      if: steps.cached-dependencies.outputs.cache-hit != 'true'
      run: |
        cd $HOME
        git clone https://www.github.com/ERGO-Code/HiGHS.git
        cmake -E make_directory ./HiGHS/build
        cd ./HiGHS
        git checkout install
        cd ./build
        ls

    # Fast build only.
    - name: Build HiGHS release
      run: |
        cd $HOME/HiGHS/build
        ls
        cmake -DFAST_BUILD=ON -DCMAKE_INSTALL_PREFIX=. ..  
        cmake --build . --config Release --parallel

    - name: Test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd $HOME/HiGHS/build
        ctest
        cmake --install .

    - name: Default Build Pre R (non-fast)
      run: |
        cd $HOME/HiGHS
        mkdir build_non_fast
        cd build_non_fast
        cmake -DCMAKE_INSTALL_PREFIX=. ..
        cmake --build . --config Release --parallel

    - name: Test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd $HOME/HiGHS/build_non_fast
        ctest


    # cmake --install .
    # does not work on linux with FAST_BUILD=OFF